config/routes.rb
VeterinaryApp::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :appointments
  resources :pets
  resources :doctors
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'appointments#new',     via: 'get'

   root 'appointments#index'

  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
  validates :name,  presence: true, length: { maximum: 35 }
  validates :zip, length: { minimum: 5 },length: { maximum: 5 }
  validates_inclusion_of :experience, in: 1..100
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  #before_action :signed_in_doctor,  only: [:index, :edit, :update, :destroy]
  #before_action :correct_doctor,   only: [:edit, :update]
  #before_action :admin_doctor,     only: :destroy
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)


    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
  def signed_in_doctor
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_doctor
    @doctor = Doctor.find(params[:id])
    redirect_to(root_url) unless current_doctor?(@doctor)
  end

  def admin_doctor
    redirect_to(root_url) unless current_doctor.admin?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :email, :password_digest, :address, :city, :state, :zip, :school, :experience)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(doctor,options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(doctor.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>School</th>
      <th>Experience</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.city %></td>
        <td><%= doctor.state %></td>
        <td><%= doctor.zip %></td>
        <td><%= doctor.school %></td>
        <td><%= doctor.experience %></td>

        <td><%= link_to 'Show', doctor %></td>
        <% if (Doctor.find(session[:doctor_id])[:admin]) %>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if (Doctor.find(session[:doctor_id])[:admin]) %>
<%= link_to 'New Doctor', new_doctor_path %>
<% end %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @doctor.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @doctor.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @doctor.zip %>
</p>

<p>
  <strong>School:</strong>
  <%= @doctor.school %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @doctor.experience %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>