config/routes.rb
VeterinaryApp::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :appointments
  resources :pets
  resources :doctors
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'appointments#new',     via: 'get'

   root 'appointments#index'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validate :visit_date_cannot_be_in_the_past
  def visit_date_cannot_be_in_the_past
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "can't be in the past")
    end
  end
  belongs_to :doctor
  belongs_to :pet
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.doctor_id = params[:doctor][:doctor_id]
    @appointment.pet_id = params[:pet][:pet_id]

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:visit_date, :reminder_appo, :rason_visit, :doctor_id, :pet_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visit_date %><br>
    <%= f.date_select :visit_date %>
  </div>
  <div class="field">
    <%= f.label :reminder_appo %><br>
    <%= f.check_box :reminder_appo %>
  </div>
  <div class="field">
    <%= f.label :rason_visit %><br>
    <%= f.text_area :rason_visit %>
  </div>
  <div class="field">
    <%= f.label :doctor %><br>
    <%= collection_select(:doctor, :doctor_id, Doctor.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= collection_select(:pet, :pet_id, Pet.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Pet</th>
      <th>Visit date</th>
      <th>Rason visit</th>
      <% if (session[:doctor_id] != nil) %>
      <th>Doctor</th>
      <th>Reminder appo</th>
      <th>Customer</th>
      <% end %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.pet.name %></td>
        <td><%= appointment.visit_date %></td>
        <td><%= appointment.rason_visit %></td>
        <% if (session[:doctor_id] != nil) %>
        <td><%= appointment.doctor.name %></td>
        <td><%= appointment.reminder_appo %></td>
        <td><%= appointment.pet.customer %></td>
       <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if (session[:doctor_id] != nil) %>
<%= link_to 'New Appointment', new_appointment_path %>
<% end %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Visit date:</strong>
  <%= @appointment.visit_date %>
</p>

<p>
  <strong>Reminder appo:</strong>
  <%= @appointment.reminder_appo %>
</p>

<p>
  <strong>Rason visit:</strong>
  <%= @appointment.rason_visit %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.name %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet.name %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |

<%= link_to 'Back', appointments_path %>