config/routes.rb
VeterinaryApp::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :appointments
  resources :pets
  resources :doctors
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'appointments#new',     via: 'get'

   root 'appointments#index'

  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Veterinary", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Appointments", root_path %></li>

          <% if session[:doctor_id] != nil %>
              <li><%= link_to "Logout", signin_path %></li>
              <li><%= link_to "Users", doctors_path %></li>
              <li><%= link_to "Pets", pets_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout", signin_path %></li>
                  <li><%= link_to "Users", doctors_path %></li>
                  <li><%= link_to "Pets", pets_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Veterinary practice</title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>

</div>
</body>
</html>